export const metadata = {
  title: "Recipes",
  description: "Generated by Next.js",
};

import "~/styles/globals.css";
import TrpcProvider from "./trpcProvider";

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <TrpcProvider>
        <body>{children}</body>
      </TrpcProvider>
    </html>
  );
}

export default RootLayout;
